/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package indice_desarrollo_humano;

/**
 *
 * @author Javith
 */
public class GUI_MAPA extends javax.swing.JFrame {

    

    /**
     * Creates new form GUI_MAPA
     */
    public GUI_MAPA() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAlajuela = new javax.swing.JButton();
        btnCartago = new javax.swing.JButton();
        btnGuanacaste = new javax.swing.JButton();
        btnHeredia = new javax.swing.JButton();
        btnLimon = new javax.swing.JButton();
        btnPuntarenas = new javax.swing.JButton();
        btnSanJose = new javax.swing.JButton();
        lAlajuela1 = new javax.swing.JLabel();
        lAlajuela0 = new javax.swing.JLabel();
        lAlajuela2 = new javax.swing.JLabel();
        lAlajuela3 = new javax.swing.JLabel();
        lAlajuela4 = new javax.swing.JLabel();
        lAlajuela5 = new javax.swing.JLabel();
        lHeredia0 = new javax.swing.JLabel();
        lHeredia1 = new javax.swing.JLabel();
        lHeredia2 = new javax.swing.JLabel();
        lCartago0 = new javax.swing.JLabel();
        lCartago1 = new javax.swing.JLabel();
        lCartago2 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 580));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 552));
        jPanel1.setLayout(null);

        btnAlajuela.setText("1-Alajuela");
        btnAlajuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlajuelaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlajuela);
        btnAlajuela.setBounds(10, 250, 110, 23);

        btnCartago.setText("2-Cartago");
        btnCartago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartagoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCartago);
        btnCartago.setBounds(10, 280, 110, 23);

        btnGuanacaste.setText("3-Guanacaste");
        btnGuanacaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuanacasteActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuanacaste);
        btnGuanacaste.setBounds(10, 310, 110, 23);

        btnHeredia.setText("4-Heredia");
        btnHeredia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHerediaActionPerformed(evt);
            }
        });
        jPanel1.add(btnHeredia);
        btnHeredia.setBounds(10, 340, 110, 23);

        btnLimon.setText("5-Limón");
        btnLimon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimonActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimon);
        btnLimon.setBounds(10, 370, 110, 23);

        btnPuntarenas.setText("6-Puntarenas");
        btnPuntarenas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntarenasActionPerformed(evt);
            }
        });
        jPanel1.add(btnPuntarenas);
        btnPuntarenas.setBounds(10, 400, 110, 23);

        btnSanJose.setText("7-San José");
        btnSanJose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanJoseActionPerformed(evt);
            }
        });
        jPanel1.add(btnSanJose);
        btnSanJose.setBounds(10, 430, 110, 23);

        lAlajuela1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        lAlajuela1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lAlajuela1MouseClicked(evt);
            }
        });
        jPanel1.add(lAlajuela1);
        lAlajuela1.setBounds(220, 70, 50, 70);

        lAlajuela0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lAlajuela0MouseClicked(evt);
            }
        });
        jPanel1.add(lAlajuela0);
        lAlajuela0.setBounds(270, 100, 50, 130);

        lAlajuela2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        lAlajuela2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lAlajuela2MouseClicked(evt);
            }
        });
        jPanel1.add(lAlajuela2);
        lAlajuela2.setBounds(150, 60, 30, 40);

        lAlajuela3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        lAlajuela3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lAlajuela3MouseClicked(evt);
            }
        });
        jPanel1.add(lAlajuela3);
        lAlajuela3.setBounds(270, 70, 30, 30);

        lAlajuela4.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        lAlajuela4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lAlajuela4MouseClicked(evt);
            }
        });
        jPanel1.add(lAlajuela4);
        lAlajuela4.setBounds(190, 80, 30, 30);

        lAlajuela5.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        lAlajuela5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lAlajuela5MouseClicked(evt);
            }
        });
        jPanel1.add(lAlajuela5);
        lAlajuela5.setBounds(230, 140, 30, 30);
        jPanel1.add(lHeredia0);
        lHeredia0.setBounds(330, 200, 10, 30);
        jPanel1.add(lHeredia1);
        lHeredia1.setBounds(370, 110, 20, 10);
        jPanel1.add(lHeredia2);
        lHeredia2.setBounds(330, 110, 40, 80);
        jPanel1.add(lCartago0);
        lCartago0.setBounds(360, 230, 100, 10);
        jPanel1.add(lCartago1);
        lCartago1.setBounds(370, 260, 70, 20);
        jPanel1.add(lCartago2);
        lCartago2.setBounds(350, 240, 100, 20);

        Fondo.setBackground(new java.awt.Color(153, 0, 153));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indice_desarrollo_humano/Provincias_de_costa_Rica.png"))); // NOI18N
        jPanel1.add(Fondo);
        Fondo.setBounds(0, 0, 600, 550);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlajuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlajuelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlajuelaActionPerformed

    private void btnCartagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCartagoActionPerformed

    private void btnGuanacasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuanacasteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuanacasteActionPerformed

    private void btnHerediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHerediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHerediaActionPerformed

    private void btnLimonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimonActionPerformed

    private void btnPuntarenasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntarenasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPuntarenasActionPerformed

    private void btnSanJoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanJoseActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new GUI_SanJose().setVisible(true);
        });
    }//GEN-LAST:event_btnSanJoseActionPerformed

    private void lAlajuela1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lAlajuela1MouseClicked
        java.awt.EventQueue.invokeLater(() -> {
            new GUI_SanJose().setVisible(true);
        });         // TODO add your handling code here:
    }//GEN-LAST:event_lAlajuela1MouseClicked

    private void lAlajuela0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lAlajuela0MouseClicked
        java.awt.EventQueue.invokeLater(() -> {
            new GUI_SanJose().setVisible(true);
        });        // TODO add your handling code here:
    }//GEN-LAST:event_lAlajuela0MouseClicked

    private void lAlajuela2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lAlajuela2MouseClicked
        java.awt.EventQueue.invokeLater(() -> {
            new GUI_SanJose().setVisible(true);
        });        // TODO add your handling code here:
    }//GEN-LAST:event_lAlajuela2MouseClicked

    private void lAlajuela3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lAlajuela3MouseClicked
        java.awt.EventQueue.invokeLater(() -> {
            new GUI_SanJose().setVisible(true);
        });        // TODO add your handling code here:
    }//GEN-LAST:event_lAlajuela3MouseClicked

    private void lAlajuela4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lAlajuela4MouseClicked
        java.awt.EventQueue.invokeLater(() -> {
            new GUI_SanJose().setVisible(true);
        });        // TODO add your handling code here:
    }//GEN-LAST:event_lAlajuela4MouseClicked

    private void lAlajuela5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lAlajuela5MouseClicked
        java.awt.EventQueue.invokeLater(() -> {
            new GUI_SanJose().setVisible(true);
        });        // TODO add your handling code here:
    }//GEN-LAST:event_lAlajuela5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_MAPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_MAPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_MAPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_MAPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI_MAPA().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnAlajuela;
    private javax.swing.JButton btnCartago;
    private javax.swing.JButton btnGuanacaste;
    private javax.swing.JButton btnHeredia;
    private javax.swing.JButton btnLimon;
    private javax.swing.JButton btnPuntarenas;
    private javax.swing.JButton btnSanJose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lAlajuela0;
    private javax.swing.JLabel lAlajuela1;
    private javax.swing.JLabel lAlajuela2;
    private javax.swing.JLabel lAlajuela3;
    private javax.swing.JLabel lAlajuela4;
    private javax.swing.JLabel lAlajuela5;
    private javax.swing.JLabel lCartago0;
    private javax.swing.JLabel lCartago1;
    private javax.swing.JLabel lCartago2;
    private javax.swing.JLabel lHeredia0;
    private javax.swing.JLabel lHeredia1;
    private javax.swing.JLabel lHeredia2;
    // End of variables declaration//GEN-END:variables
}
