/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package indice_desarrollo_humano;

import javax.swing.JOptionPane;

/**
 *
 * @author Javith
 */
public class GUI_SanJose extends javax.swing.JFrame {
    public static Logica logica;
    
    /**
     * Creates new form GUI_MAPA
     */
    public GUI_SanJose() {
        initComponents();
        logica = new Logica("Cantones/San Jose");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        label0 = new javax.swing.JButton();
        label1 = new javax.swing.JButton();
        label2 = new javax.swing.JButton();
        label3 = new javax.swing.JButton();
        label4 = new javax.swing.JButton();
        label5 = new javax.swing.JButton();
        label6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        label7 = new javax.swing.JButton();
        label8 = new javax.swing.JButton();
        label9 = new javax.swing.JButton();
        label10 = new javax.swing.JButton();
        label11 = new javax.swing.JButton();
        label12 = new javax.swing.JButton();
        label13 = new javax.swing.JButton();
        label14 = new javax.swing.JButton();
        label15 = new javax.swing.JButton();
        label16 = new javax.swing.JButton();
        label17 = new javax.swing.JButton();
        label18 = new javax.swing.JButton();
        label19 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 580));
        setPreferredSize(new java.awt.Dimension(590, 625));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 552));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(241, 238, 238));

        label0.setText("1-San José");
        label0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label0ActionPerformed(evt);
            }
        });
        jPanel3.add(label0);

        label1.setText("2-Escazú");
        label1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label1ActionPerformed(evt);
            }
        });
        jPanel3.add(label1);

        label2.setText("3-Desamparados");
        label2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label2ActionPerformed(evt);
            }
        });
        jPanel3.add(label2);

        label3.setText("4-Puriscal");
        label3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label3ActionPerformed(evt);
            }
        });
        jPanel3.add(label3);

        label4.setText("5-Tarrazú");
        label4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label4ActionPerformed(evt);
            }
        });
        jPanel3.add(label4);

        label5.setText("6-Aserrí");
        label5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label5ActionPerformed(evt);
            }
        });
        jPanel3.add(label5);

        label6.setText("7-Mora");
        label6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label6ActionPerformed(evt);
            }
        });
        jPanel3.add(label6);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(340, 20, 130, 230);

        jPanel2.setBackground(new java.awt.Color(241, 238, 238));

        label7.setText("8-Goicoechea");
        label7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label7ActionPerformed(evt);
            }
        });
        jPanel2.add(label7);

        label8.setText("9-Santa Ana");
        label8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label8ActionPerformed(evt);
            }
        });
        jPanel2.add(label8);

        label9.setText("10-Alajuelita");
        label9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label9ActionPerformed(evt);
            }
        });
        jPanel2.add(label9);

        label10.setText("11-V. Coronado");
        label10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label10ActionPerformed(evt);
            }
        });
        jPanel2.add(label10);

        label11.setText("12-Acosta");
        label11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label11ActionPerformed(evt);
            }
        });
        jPanel2.add(label11);

        label12.setText("13-Tibás");
        label12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label12ActionPerformed(evt);
            }
        });
        jPanel2.add(label12);

        label13.setText("14-Moravia");
        label13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label13ActionPerformed(evt);
            }
        });
        jPanel2.add(label13);

        label14.setText("15-M. Oca");
        label14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label14ActionPerformed(evt);
            }
        });
        jPanel2.add(label14);

        label15.setText("16-Turrubares");
        label15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label15ActionPerformed(evt);
            }
        });
        jPanel2.add(label15);

        label16.setText("17-Dota");
        label16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label16ActionPerformed(evt);
            }
        });
        jPanel2.add(label16);

        label17.setText("18-Curridabat");
        label17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label17ActionPerformed(evt);
            }
        });
        jPanel2.add(label17);

        label18.setText("19-P.Zeledón");
        label18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label18ActionPerformed(evt);
            }
        });
        jPanel2.add(label18);

        label19.setText("20-León Cortes");
        label19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label19ActionPerformed(evt);
            }
        });
        jPanel2.add(label19);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(480, 20, 110, 440);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("San José");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 20, 120, 80);

        Fondo.setBackground(new java.awt.Color(153, 0, 153));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indice_desarrollo_humano/SanJose.jpg"))); // NOI18N
        jPanel1.add(Fondo);
        Fondo.setBounds(0, 0, 600, 490);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label15ActionPerformed
        logica.abrirVentana(16);                // TODO add your handling code here:
    }//GEN-LAST:event_label15ActionPerformed

    private void label0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label0ActionPerformed
        logica.abrirVentana(1);                // TODO add your handling code here:
    }//GEN-LAST:event_label0ActionPerformed

    private void label1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label1ActionPerformed
         logica.abrirVentana(2);        // TODO add your handling code here:
    }//GEN-LAST:event_label1ActionPerformed

    private void label2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label2ActionPerformed
          logica.abrirVentana(3);       // TODO add your handling code here:
    }//GEN-LAST:event_label2ActionPerformed

    private void label3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label3ActionPerformed
          logica.abrirVentana(4);     // TODO add your handling code here:
    }//GEN-LAST:event_label3ActionPerformed

    private void label4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label4ActionPerformed
          logica.abrirVentana(5);        // TODO add your handling code here:
    }//GEN-LAST:event_label4ActionPerformed

    private void label5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label5ActionPerformed
          logica.abrirVentana(6);        // TODO add your handling code here:
    }//GEN-LAST:event_label5ActionPerformed

    private void label6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label6ActionPerformed
          logica.abrirVentana(7);        // TODO add your handling code here:
    }//GEN-LAST:event_label6ActionPerformed

    private void label7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label7ActionPerformed
             logica.abrirVentana(8);        // TODO add your handling code here:
    }//GEN-LAST:event_label7ActionPerformed

    private void label8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label8ActionPerformed
            logica.abrirVentana(9); // TODO add your handling code here:
    }//GEN-LAST:event_label8ActionPerformed

    private void label9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label9ActionPerformed
            logica.abrirVentana(10);    // TODO add your handling code here:
    }//GEN-LAST:event_label9ActionPerformed

    private void label10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label10ActionPerformed
            logica.abrirVentana(11);        // TODO add your handling code here:
    }//GEN-LAST:event_label10ActionPerformed

    private void label11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label11ActionPerformed
            logica.abrirVentana(12);         // TODO add your handling code here:
    }//GEN-LAST:event_label11ActionPerformed

    private void label12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label12ActionPerformed
            logica.abrirVentana(13);         // TODO add your handling code here:
    }//GEN-LAST:event_label12ActionPerformed

    private void label13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label13ActionPerformed
            logica.abrirVentana(14);         // TODO add your handling code here:
    }//GEN-LAST:event_label13ActionPerformed

    private void label14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label14ActionPerformed
            logica.abrirVentana(15);         // TODO add your handling code here:
    }//GEN-LAST:event_label14ActionPerformed

    private void label16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label16ActionPerformed
            logica.abrirVentana(17);         // TODO add your handling code here:
    }//GEN-LAST:event_label16ActionPerformed

    private void label17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label17ActionPerformed
            logica.abrirVentana(18);                 // TODO add your handling code here:
    }//GEN-LAST:event_label17ActionPerformed

    private void label18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label18ActionPerformed
            logica.abrirVentana(19);         // TODO add your handling code here:
    }//GEN-LAST:event_label18ActionPerformed

    private void label19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label19ActionPerformed
           logica.abrirVentana(20);         // TODO add your handling code here:
    }//GEN-LAST:event_label19ActionPerformed

    /**
     * @param args the command line arguments
     */
    
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton label0;
    private javax.swing.JButton label1;
    private javax.swing.JButton label10;
    private javax.swing.JButton label11;
    private javax.swing.JButton label12;
    private javax.swing.JButton label13;
    private javax.swing.JButton label14;
    private javax.swing.JButton label15;
    private javax.swing.JButton label16;
    private javax.swing.JButton label17;
    private javax.swing.JButton label18;
    private javax.swing.JButton label19;
    private javax.swing.JButton label2;
    private javax.swing.JButton label3;
    private javax.swing.JButton label4;
    private javax.swing.JButton label5;
    private javax.swing.JButton label6;
    private javax.swing.JButton label7;
    private javax.swing.JButton label8;
    private javax.swing.JButton label9;
    // End of variables declaration//GEN-END:variables
}
